name: Cypress Projeleri

on:
  push:
    branches:
      - main:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: adım1
      - uses: actions/checkout@v4

      - name: adım2
      - uses: cypress-io/github-action@v5      